language: php

sudo: false # checking if sudo makes behat error go away.

addons:
  postgresql: "9.6"
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java9-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.1
 - 7.2

env:
 global:
  - IGNORE_PATHS=checkboxgroup/checkboxgroup.php # we know this dir is problematic
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE MOODLE_CI_VER=2
  - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE MOODLE_CI_VER=2
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE MOODLE_CI_VER=2
  - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE MOODLE_CI_VER=2

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install v8.9.4
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
script:
  - moodle-plugin-ci phplint
  #- moodle-plugin-ci phpcpd # bug#1065 as discussed.
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
