<?php
// This file is part of mod_datalynx for Moodle - http://moodle.org/
//
// It is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// It is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace datalynxfield_number;

/**
 * Field format implementation for number fields.
 *
 * Carries two independent concerns:
 *  - `decimals`, the display-mode precision (see {@see renderer::render_display_mode()});
 *  - `inputtype`, which optionally turns the edit-mode input into a slider whose selectable values
 *    are generated by {@see self::get_slider_values()}.
 *
 * @package    datalynxfield_number
 * @copyright  2026 David Bogner
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class field_format extends \mod_datalynx\local\field_format\base {
    /** @var string Plain number input, the default edit-mode rendering. */
    public const INPUT_TEXT = '';

    /** @var string Slider edit-mode rendering. */
    public const INPUT_SLIDER = 'slider';

    /** @var string Uniform steps of the configured step size. */
    public const SCALE_LINEAR = 'linear';

    /** @var string Fibonacci numbers within the configured range. */
    public const SCALE_FIBONACCI = 'fibonacci';

    /** @var string 1-2-5 series (1, 2, 5, 10, 20, 50, ...) within the configured range. */
    public const SCALE_ONETWOFIVE = 'onetwofive';

    /** @var int Hard cap on the number of generated slider values. */
    public const MAX_SLIDER_VALUES = 500;

    /**
     * The edit-mode input types a format can choose from.
     *
     * @return array Input type => human readable name.
     */
    public static function get_input_types(): array {
        return [
            self::INPUT_TEXT => get_string('fieldformatinputtypetext', 'datalynxfield_number'),
            self::INPUT_SLIDER => get_string('fieldformatinputtypeslider', 'datalynxfield_number'),
        ];
    }

    /**
     * The value sequences a slider can step through.
     *
     * @return array Scale => human readable name.
     */
    public static function get_slider_scales(): array {
        return [
            self::SCALE_LINEAR => get_string('fieldformatsliderscalelinear', 'datalynxfield_number'),
            self::SCALE_FIBONACCI => get_string('fieldformatsliderscalefibonacci', 'datalynxfield_number'),
            self::SCALE_ONETWOFIVE => get_string('fieldformatsliderscaleonetwofive', 'datalynxfield_number'),
        ];
    }

    /**
     * Defines configuration elements on the form.
     *
     * @param \MoodleQuickForm $mform
     */
    public function config_form(\MoodleQuickForm &$mform) {
        self::define_elements($mform);
    }

    /**
     * Adds every configuration element of this format to a form.
     *
     * Shared by {@see self::config_form()} and
     * {@see \datalynxfield_number\form\field_format_form::format_definition()} so the definition
     * rendered by fieldformat/edit.php cannot drift from the one declared by the format class.
     *
     * @param \MoodleQuickForm $mform
     * @return void
     */
    public static function define_elements(\MoodleQuickForm &$mform): void {
        $mform->addElement(
            'text',
            'decimals',
            get_string('fieldformatdecimals', 'datalynxfield_number'),
            ['size' => 3]
        );
        $mform->setType('decimals', PARAM_INT);
        $mform->addHelpButton('decimals', 'fieldformatdecimals', 'datalynxfield_number');

        $mform->addElement(
            'select',
            'inputtype',
            get_string('fieldformatinputtype', 'datalynxfield_number'),
            self::get_input_types()
        );
        $mform->setType('inputtype', PARAM_ALPHA);
        $mform->addHelpButton('inputtype', 'fieldformatinputtype', 'datalynxfield_number');

        $mform->addElement(
            'text',
            'sliderstart',
            get_string('fieldformatsliderstart', 'datalynxfield_number'),
            ['size' => 8]
        );
        $mform->setType('sliderstart', PARAM_RAW_TRIMMED);
        $mform->addHelpButton('sliderstart', 'fieldformatsliderstart', 'datalynxfield_number');
        $mform->hideIf('sliderstart', 'inputtype', 'neq', self::INPUT_SLIDER);

        $mform->addElement(
            'text',
            'sliderend',
            get_string('fieldformatsliderend', 'datalynxfield_number'),
            ['size' => 8]
        );
        $mform->setType('sliderend', PARAM_RAW_TRIMMED);
        $mform->addHelpButton('sliderend', 'fieldformatsliderend', 'datalynxfield_number');
        $mform->hideIf('sliderend', 'inputtype', 'neq', self::INPUT_SLIDER);

        $mform->addElement(
            'select',
            'sliderscale',
            get_string('fieldformatsliderscale', 'datalynxfield_number'),
            self::get_slider_scales()
        );
        $mform->setType('sliderscale', PARAM_ALPHA);
        $mform->addHelpButton('sliderscale', 'fieldformatsliderscale', 'datalynxfield_number');
        $mform->hideIf('sliderscale', 'inputtype', 'neq', self::INPUT_SLIDER);

        $mform->addElement(
            'text',
            'sliderstep',
            get_string('fieldformatsliderstep', 'datalynxfield_number'),
            ['size' => 8]
        );
        $mform->setType('sliderstep', PARAM_RAW_TRIMMED);
        $mform->setDefault('sliderstep', 1);
        $mform->addHelpButton('sliderstep', 'fieldformatsliderstep', 'datalynxfield_number');
        $mform->hideIf('sliderstep', 'inputtype', 'neq', self::INPUT_SLIDER);
        $mform->hideIf('sliderstep', 'sliderscale', 'neq', self::SCALE_LINEAR);

        $mform->addElement(
            'text',
            'sliderunit',
            get_string('fieldformatsliderunit', 'datalynxfield_number'),
            ['size' => 12]
        );
        $mform->setType('sliderunit', PARAM_TEXT);
        $mform->addHelpButton('sliderunit', 'fieldformatsliderunit', 'datalynxfield_number');
        $mform->hideIf('sliderunit', 'inputtype', 'neq', self::INPUT_SLIDER);

        $mform->addElement(
            'advcheckbox',
            'sliderticks',
            get_string('fieldformatsliderticks', 'datalynxfield_number')
        );
        $mform->setType('sliderticks', PARAM_INT);
        $mform->addHelpButton('sliderticks', 'fieldformatsliderticks', 'datalynxfield_number');
        $mform->hideIf('sliderticks', 'inputtype', 'neq', self::INPUT_SLIDER);
    }

    /**
     * Validates configuration options.
     *
     * @param array $data Form data.
     * @param array $files Uploaded files.
     * @return array Validation errors.
     */
    public function validation(array $data, array $files): array {
        return self::validate_settings($data);
    }

    /**
     * Validates the submitted format settings.
     *
     * Only the slider settings are checked, and only when the slider input type is selected —
     * leftover slider values from a format that has been switched back to a plain input must not
     * block saving.
     *
     * @param array $data Form data.
     * @return array Validation errors, keyed by element name.
     */
    public static function validate_settings(array $data): array {
        $errors = [];

        if (($data['inputtype'] ?? self::INPUT_TEXT) !== self::INPUT_SLIDER) {
            return $errors;
        }

        $start = $data['sliderstart'] ?? '';
        $end = $data['sliderend'] ?? '';
        $scale = $data['sliderscale'] ?? self::SCALE_LINEAR;
        $step = $data['sliderstep'] ?? '';

        if (!is_numeric($start)) {
            $errors['sliderstart'] = get_string('errnumeric', 'datalynx');
        }
        if (!is_numeric($end)) {
            $errors['sliderend'] = get_string('errnumeric', 'datalynx');
        }
        if (isset($errors['sliderstart']) || isset($errors['sliderend'])) {
            return $errors;
        }

        if ((float) $start >= (float) $end) {
            $errors['sliderend'] = get_string('errorsliderrange', 'datalynxfield_number');
            return $errors;
        }

        if ($scale === self::SCALE_LINEAR) {
            if (!is_numeric($step) || (float) $step <= 0) {
                $errors['sliderstep'] = get_string('errorsliderstep', 'datalynxfield_number');
                return $errors;
            }
        }

        $values = self::generate_slider_values((float) $start, (float) $end, $scale, (float) $step);
        if (count($values) < 2) {
            $errors['sliderscale'] = get_string('errorslidernovalues', 'datalynxfield_number');
        } else if (count($values) >= self::MAX_SLIDER_VALUES) {
            $errors['sliderstep'] = get_string(
                'errorslidertoomanyvalues',
                'datalynxfield_number',
                self::MAX_SLIDER_VALUES
            );
        }

        return $errors;
    }

    /**
     * Whether this format renders the edit-mode input as a slider.
     *
     * @return bool
     */
    public function is_slider(): bool {
        return $this->get_setting('inputtype', self::INPUT_TEXT) === self::INPUT_SLIDER;
    }

    /**
     * The ordered list of values this format's slider can be set to.
     *
     * Returns an empty array when the format is not configured as a slider or the configuration
     * does not yield at least two values; callers fall back to the plain number input in that case.
     *
     * @return float[]
     */
    public function get_slider_values(): array {
        if (!$this->is_slider()) {
            return [];
        }

        $start = $this->get_setting('sliderstart', '');
        $end = $this->get_setting('sliderend', '');
        if (!is_numeric($start) || !is_numeric($end)) {
            return [];
        }

        $values = self::generate_slider_values(
            (float) $start,
            (float) $end,
            (string) $this->get_setting('sliderscale', self::SCALE_LINEAR),
            (float) $this->get_setting('sliderstep', 1)
        );

        return count($values) < 2 ? [] : $values;
    }

    /**
     * Builds the selectable values of a slider between two bounds.
     *
     * The linear scale walks from $start in $step increments. The Fibonacci and 1-2-5 scales always
     * start at $start and then append the sequence members that lie above it, so the lowest position
     * of the slider is the configured start value. Neither sequence appends $end: the highest
     * selectable value is the last sequence member that does not exceed it (0..50 on the Fibonacci
     * scale ends at 34).
     *
     * @param float $start Lower bound, always the first value.
     * @param float $end Upper bound, never exceeded.
     * @param string $scale One of the SCALE_* constants.
     * @param float $step Increment for the linear scale, ignored otherwise.
     * @return float[] Ascending list of values, capped at MAX_SLIDER_VALUES entries.
     */
    public static function generate_slider_values(
        float $start,
        float $end,
        string $scale,
        float $step = 1.0
    ): array {
        if ($start >= $end) {
            return [];
        }

        if ($scale === self::SCALE_LINEAR) {
            if ($step <= 0) {
                return [];
            }
            // Round every value to the precision of the step so that accumulating fractional steps
            // does not produce values such as 0.30000000000000004.
            $precision = self::get_precision($step);
            $epsilon = $step / 1000;
            $values = [];
            for ($i = 0; count($values) < self::MAX_SLIDER_VALUES; $i++) {
                $value = $start + ($i * $step);
                if ($value > $end + $epsilon) {
                    break;
                }
                $values[] = round($value, $precision);
            }
            return $values;
        }

        $sequence = $scale === self::SCALE_FIBONACCI
            ? self::fibonacci_sequence($end)
            : self::onetwofive_sequence($end);

        $values = [$start];
        foreach ($sequence as $value) {
            if ($value <= $start) {
                continue;
            }
            if ($value > $end) {
                break;
            }
            $values[] = $value;
            if (count($values) >= self::MAX_SLIDER_VALUES) {
                break;
            }
        }

        return $values;
    }

    /**
     * Fibonacci numbers up to (and including) a maximum.
     *
     * Starts 1, 2, 3, 5, 8 — the duplicated leading 1 of the mathematical sequence is skipped so
     * that no value appears twice on the slider.
     *
     * @param float $max Highest value to generate.
     * @return float[]
     */
    protected static function fibonacci_sequence(float $max): array {
        $sequence = [];
        $previous = 1.0;
        $current = 2.0;
        if ($max >= 1) {
            $sequence[] = 1.0;
        }
        while ($current <= $max && count($sequence) < self::MAX_SLIDER_VALUES) {
            $sequence[] = $current;
            [$previous, $current] = [$current, $previous + $current];
        }
        return $sequence;
    }

    /**
     * The 1-2-5 series (1, 2, 5, 10, 20, 50, 100, ...) up to (and including) a maximum.
     *
     * @param float $max Highest value to generate.
     * @return float[]
     */
    protected static function onetwofive_sequence(float $max): array {
        $sequence = [];
        $magnitude = 1.0;
        while ($magnitude <= $max && count($sequence) < self::MAX_SLIDER_VALUES) {
            foreach ([1, 2, 5] as $mantissa) {
                $value = $mantissa * $magnitude;
                if ($value > $max) {
                    return $sequence;
                }
                $sequence[] = $value;
                if (count($sequence) >= self::MAX_SLIDER_VALUES) {
                    return $sequence;
                }
            }
            $magnitude *= 10;
        }
        return $sequence;
    }

    /**
     * Number of decimal places a value carries, capped at 6.
     *
     * @param float $value
     * @return int
     */
    protected static function get_precision(float $value): int {
        $asstring = rtrim(rtrim(sprintf('%.6F', $value), '0'), '.');
        $dot = strpos($asstring, '.');
        return $dot === false ? 0 : strlen($asstring) - $dot - 1;
    }

    /**
     * Get legacy/default settings for name.
     *
     * @param string $name
     * @return array
     */
    public function get_default_settings_for_name(string $name): array {
        if (is_numeric($name)) {
            return ['decimals' => (int)$name];
        }
        return [];
    }
}
