name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  ci:
    uses: Wunderbyte-GmbH/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
      # Change these based on your plugin's requirements

      disable_release: true  # Use true if using the tag-based release workflow

      # moodle_branches: "MOODLE_401_STABLE MOODLE_402_STABLE"  # Optional: Only test specific Moodle versions
      # min_php: "7.4"  # Optional: Set minimum PHP version

      # Command to install more dependencies
      # extra_plugin_runners: |
      #   moodle-plugin-ci add-plugin --branch main Wunderbyte-GmbH/moodle-local_wunderbyte_table
      #   moodle-plugin-ci add-plugin --branch master branchup/moodle-filter_shortcodes

      # If you need to ignore specific paths (third-party libraries are ignored by default)
      # ignore_paths: 'vue3,moodle/tests/fixtures,moodle/Sniffs,moodle/vue3,OpenTBS,TinyButStrong'

      # If you need to ignore specific names (third-party libraries are ignored by default)
      # ignore_names: '*.txt,fallback.css'

      # Specify paths to ignore for mustache lint
      # mustache_ignore_names: 'cashier.mustache,shopping_cart_item.mustache,history_item.mustache,form-user-selector-suggestion.mustache,shopping_cart_popover.mustache'

      # Specify paths to ignore for code checker
      # codechecker_ignore_paths: 'OpenTBS, TinyButStrong'

      # Specify paths to ignore for PHPDoc checker
      # phpdocchecker_ignore_paths: 'OpenTBS, TinyButStrong'

      # If you need to disable specific tests
      # disable_phpunit: true
      # disable_behat: true
      # disable_grunt: true
      # disable_phpcpd: true
      # disable_phpdoc: true
      # disable_phpcs: true
      # disable_phplint: true
      # disable_mustache: true
      # disable_ci_validate: true

      # If you need to enable PHPMD
      enable_phpmd: true

      # For strict code quality checks
      codechecker_max_warnings: 0

      # Override to exclude stale AMD file check (similar to your current workaround)
      # This might not be needed with the reusable workflow as it might handle this already
